### ISSUE TITLE
BBS docker-compose.yml settings

### ISSUE THREAD

**Issue by huan** [zixia/bbs.zixia.net#11]
```yaml
version: '3.8'
services:

  bbs:
    image: ghcr.io/zixia/bbs.zixia.net
    container_name: bbs
    network_mode: bridge
    hostname: bbs.zixia.net
    # ⬇️  
    #   https://github.com/docker/compose/issues/4729#issuecomment-436148318
    #   https://medium.com/@junwan01/quote-your-ports-in-docker-compose-file-34d9505999ad
    ports:
      - '22:22'
      - '23:23'
      - '2222:2222'
    expose:
      - 80
    volumes:
      - /data/bbs/:/bbs
    environment:
      TZ: "Asia/Shanghai"
      VIRTUAL_HOST: 'bbs.zixia.net,*.bbs.zixia.net,wforum.zixia.net,*.wforum.zixia.net'
      LETSENCRYPT_HOST: 'bbs.zixia.net,wforum.zixia.net'
      HTTPS_METHOD: 'noredirect'
```

Read the original version at [here](https://github.com/zixia/server/blob/1dd58eaa989f9095599a759db554c64b3dcdd4d0/bbs.yml)
